name: sudanese_currency
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  # for LineChart (statestical tracking)
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  # for add multilanguage
  flutter_localizations:
    sdk: flutter
  # for vertical and horizental gap instead of Sizedbox
  gap: ^3.0.1
  # syncfusion_flutter_charts: ^26.2.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/BalooBhaijaan2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooBhaijaan2-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
